# Generated by Django 4.2.3 on 2023-10-14 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='horarios',
            field=models.ManyToManyField(related_name='horarios', to='bus.horario'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='lugar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lugar', to='bus.lugar'),
        ),
    ]
