# Generated by Django 4.2.3 on 2023-08-25 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.DateTimeField(verbose_name='Hora')),
            ],
        ),
        migrations.AlterModelOptions(
            name='busschedule',
            options={'verbose_name': 'Bus', 'verbose_name_plural': 'Buses'},
        ),
        migrations.RemoveField(
            model_name='busschedule',
            name='hora',
        ),
        migrations.AddField(
            model_name='busschedule',
            name='hora',
            field=models.ManyToManyField(to='bus.time'),
        ),
    ]
