# Generated by Django 4.2.3 on 2023-11-05 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ruta',
            old_name='bus_id',
            new_name='bus',
        ),
    ]
