# Generated by Django 4.2.3 on 2023-11-15 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_rename_bus_id_ruta_bus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autobus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chofer', models.CharField(max_length=50)),
                ('placa', models.CharField(max_length=50)),
                ('capacidad', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Autobus',
                'verbose_name_plural': 'Autobuses',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField(unique=True)),
                ('parada', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bus.parada')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sector', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectores',
            },
        ),
        migrations.RemoveField(
            model_name='ruta',
            name='bus',
        ),
        migrations.RemoveField(
            model_name='ruta',
            name='parada',
        ),
        migrations.DeleteModel(
            name='Bus',
        ),
        migrations.DeleteModel(
            name='Ruta',
        ),
        migrations.AddField(
            model_name='autobus',
            name='sector',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bus.sector'),
        ),
        migrations.AddField(
            model_name='parada',
            name='autobus',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bus.autobus'),
        ),
    ]
