# Generated by Django 4.2.3 on 2023-08-26 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_time_alter_busschedule_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busschedule',
            name='hora',
        ),
        migrations.AddField(
            model_name='busschedule',
            name='hora',
            field=models.ForeignKey(null=django.db.models.deletion.SET_NULL, on_delete=django.db.models.deletion.CASCADE, to='bus.time'),
            preserve_default=django.db.models.deletion.SET_NULL,
        ),
    ]
