# Generated by Django 4.2.3 on 2023-10-19 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0003_alter_sector_horarios_alter_sector_lugar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='lugar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='lugares', to='bus.lugar'),
        ),
    ]
