# Generated by Django 4.2.3 on 2023-08-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0004_dia_horario_horariopordia_delete_busschedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dia',
            name='nombre',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miercoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sabado')]),
        ),
    ]
