# Generated by Django 4.2.3 on 2023-08-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0005_alter_dia_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.CharField(max_length=50)),
                ('fin', models.CharField(max_length=50)),
                ('HorarioDia', models.ManyToManyField(to='bus.horariopordia')),
            ],
        ),
    ]
